### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Captain-Barge** [Amourspirit/python_libre_pythonista_ext#5]
Tried to install using [the file available here](https://extensions.libreoffice.org/en/extensions/show/99231) but I'm given the error message below. Tried checking for updates and clicking the 'enable' button with no success.

![image](https://github.com/user-attachments/assets/bd45aebb-8a05-475f-ae48-a2ca59fc2de4)

**Computer info**
- OS: Debian GNU/Linux 12 (bookworm) x86_64
- Kernel: 6.1.0-25-amd64
- DE: GNOME 43.9

**LibreOffice info**
- Version: 7.4.7.2 / LibreOffice Community
- Build ID: 40(Build:2)
- CPU threads: 4; OS: Linux 6.1; UI render: default; VCL: gtk3
- Locale: en-US (en_US.UTF-8); UI: en-US
- Debian package version: 4:7.4.7-1+deb12u4
- Calc: threaded

**Comment by Amourspirit** [comment]
I just set up a Debian virtual machine.
I comes with LibreOffice 7.4.7.2 installed.
So far I can only confirm I am getting the same issue.
I will see what I can figure out.

**Comment by Amourspirit** [comment]
I spent the last several hour trying to work out this issue.

I also noticed the [APSO](https://extensions.libreoffice.org/en/extensions/show/apso-alternative-script-organizer-for-python) extension does not install.

I also see that LibreOffice base is not installed with the Debian default LibreOffice. Base needs Java.

My Best guess is that this is due to a java issue. When I look at the java for the installed version of LibreOffice via `Tools -> Options -> Advanced`  I can see no Java enabled. There are no java vendors availalbe.

While LibrePythonista does not require or use Java, I am guesing that LibreOffice uses it with registering certain Extesion features.

I tried many things to get a java version to show up, i installed about 5 diferrent java version, I even copied the java from my Ubunt 24.04 and tried it. Nothing worked that I tried.

In the end I installed flatpak on Debian 12 and then installed LibreOffice from [flathub.org](https://flathub.org/apps/org.libreoffice.LibreOffice). Using the flatpack version of Calc, both APSO and LibrePythonista work as expected.

This does not seem to be an issue with LibrePythonista.
